name: Generate Swagger HTML

on:
  push:
    branches: [ master ]

jobs:
  generate-swagger-html:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install -g @redocly/cli

    - name: Generate HTML
      run: redocly build-docs eudamed_api_openapi_3_1.yml --output index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        keep_files: true
